import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{data}</h1>
    </div>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      data: "hello world",
    },
  };
}
