import Head from "next/head";
import { useTranslation } from "next-i18next";
import styles from "../styles/Home.module.css";
export default function Home({ data }) {
  const { t } = useTranslation();
  return (
    <div className={styles.container}>
      <Head>
        <title>{t("Services")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{data}</h1>
    </div>
  );
}

export async function getServerSideProps({ locale }) {
  return {
    props: {
      data: "hello world",
    },
  };
}
